name: test

on: [pull_request, workflow_dispatch]

jobs:

  pod-lib-lint:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Bundler
      run: bundle update --bundler
    - name: Install Ruby gems with Bundler
      run: bundle install
    - name: Lint podspec using local source
      run: pod lib lint
